param(
	[string]$OutDir = "docs\api\raw",
	[string]$MarkdownDir = "docs\api\markdown"
)

$ErrorActionPreference = "Stop"

$Root = Resolve-Path (Join-Path $PSScriptRoot "..")
$OutputDir = Join-Path $Root.Path $OutDir
$MarkdownOutputDir = Join-Path $Root.Path $MarkdownDir
$ApiDir = Split-Path -Parent $OutputDir

New-Item -ItemType Directory -Force -Path $OutputDir | Out-Null
New-Item -ItemType Directory -Force -Path $MarkdownOutputDir | Out-Null
New-Item -ItemType Directory -Force -Path $ApiDir | Out-Null

function Get-DocSymbolName {
	param(
		[Parameter(Mandatory = $true)]
		[string]$Declaration
	)

	$Parts = $Declaration -split '\s+::\s+', 2
	if ($Parts.Count -gt 1) {
		return $Parts[0].Trim()
	}

	$Words = $Declaration.Trim() -split '\s+', 2
	return $Words[0]
}

function Add-DocEntry {
	param(
		[Parameter(Mandatory = $true)]
		[hashtable]$Entries,

		[AllowNull()]
		[string]$Section,

		[AllowNull()]
		[string]$Declaration,

		[string[]]$Docs
	)

	if ([string]::IsNullOrWhiteSpace($Section) -or [string]::IsNullOrWhiteSpace($Declaration)) {
		return
	}

	$DocLines = @()
	foreach ($DocLine in $Docs) {
		if (-not [string]::IsNullOrWhiteSpace($DocLine)) {
			$DocLines += $DocLine.TrimEnd()
		}
	}

	$Entries[$Section] += [pscustomobject]@{
		Name        = Get-DocSymbolName -Declaration $Declaration
		Declaration = $Declaration.TrimEnd()
		Docs        = $DocLines
	}
}

function Convert-RawDocToMarkdown {
	param(
		[Parameter(Mandatory = $true)]
		[string]$Name,

		[Parameter(Mandatory = $true)]
		[string]$Title,

		[Parameter(Mandatory = $true)]
		[string]$RawPath
	)

	$Target = Join-Path $MarkdownOutputDir "$Name.md"
	$RawLines = Get-Content -LiteralPath $RawPath
	$PackageName = $Name
	$Entries = @{
		constants  = @()
		procedures = @()
		types      = @()
	}
	$CurrentSection = $null
	$CurrentDeclaration = $null
	$CurrentDocs = @()

	foreach ($Line in $RawLines) {
		if ($Line -match '^package\s+(.+)$') {
			$PackageName = $Matches[1].Trim()
			continue
		}

		if ($Line -match '^\t(fullpath|files):') {
			Add-DocEntry -Entries $Entries -Section $CurrentSection -Declaration $CurrentDeclaration -Docs $CurrentDocs
			$CurrentSection = $null
			$CurrentDeclaration = $null
			$CurrentDocs = @()
			continue
		}

		if ($Line -match '^\t(constants|procedures|types)$') {
			Add-DocEntry -Entries $Entries -Section $CurrentSection -Declaration $CurrentDeclaration -Docs $CurrentDocs
			$CurrentSection = $Matches[1]
			$CurrentDeclaration = $null
			$CurrentDocs = @()
			continue
		}

		if ($null -ne $CurrentSection -and $Line -match '^\t\t([^\t].*)$') {
			Add-DocEntry -Entries $Entries -Section $CurrentSection -Declaration $CurrentDeclaration -Docs $CurrentDocs
			$CurrentDeclaration = $Matches[1].TrimEnd()
			$CurrentDocs = @()
			continue
		}

		if ($null -ne $CurrentDeclaration -and $Line -match '^\t\t\t(.*)$') {
			$CurrentDocs += $Matches[1].TrimEnd()
			continue
		}
	}

	Add-DocEntry -Entries $Entries -Section $CurrentSection -Declaration $CurrentDeclaration -Docs $CurrentDocs

	$Markdown = @()
	$Markdown += "# $Title API"
	$Markdown += ""
	$Markdown += "Generated by ``tools/generate_api_docs.ps1`` from ``odin doc`` output."
	$Markdown += ""
	$Markdown += "Package: ``$PackageName``"
	$Markdown += ""

	$Sections = @(
		@{ Key = "constants"; Title = "Constants" },
		@{ Key = "procedures"; Title = "Procedures" },
		@{ Key = "types"; Title = "Types" }
	)

	foreach ($SectionInfo in $Sections) {
		$Markdown += "## $($SectionInfo.Title)"
		$Markdown += ""

		$SectionEntries = $Entries[$SectionInfo.Key]
		if ($SectionEntries.Count -eq 0) {
			$Markdown += "_No public $($SectionInfo.Title.ToLowerInvariant())._"
			$Markdown += ""
			continue
		}

		foreach ($Entry in $SectionEntries) {
			$Markdown += "### ``$($Entry.Name)``"
			$Markdown += ""
			$Markdown += '```odin'
			$Markdown += $Entry.Declaration
			$Markdown += '```'
			$Markdown += ""

			if ($Entry.Docs.Count -gt 0) {
				foreach ($DocLine in $Entry.Docs) {
					$Markdown += $DocLine
				}
				$Markdown += ""
			}
		}
	}

	while ($Markdown.Count -gt 0 -and [string]::IsNullOrWhiteSpace($Markdown[$Markdown.Count - 1])) {
		if ($Markdown.Count -eq 1) {
			$Markdown = @()
		} else {
			$Markdown = $Markdown[0..($Markdown.Count - 2)]
		}
	}

	Set-Content -LiteralPath $Target -Value $Markdown -Encoding utf8
	Write-Host "Wrote $Target"
}

function Write-OdinDoc {
	param(
		[Parameter(Mandatory = $true)]
		[string]$Name,

		[Parameter(Mandatory = $true)]
		[string]$PackagePath
	)

	$Target = Join-Path $OutputDir "$Name.txt"
	$Arguments = @(
		"doc",
		(Join-Path $Root.Path $PackagePath),
		"-collection:ape=$($Root.Path)"
	)

	$DocText = & odin @Arguments
	if ($LASTEXITCODE -ne 0) {
		throw "odin doc failed for $PackagePath with exit code $LASTEXITCODE"
	}

	if ($Name -eq "gfx_api") {
		$DocText = $DocText -replace 'Context :: struct \{[^\r\n]*\}', 'Context :: struct {...}'
	}
	$RepoPathPattern = [regex]::Escape($Root.Path.Replace("\", "/"))
	$DocText = $DocText -replace $RepoPathPattern, '<repo>'
	$RepoPathPattern = [regex]::Escape($Root.Path)
	$DocText = $DocText -replace $RepoPathPattern, '<repo>'

	$DocText | Set-Content -LiteralPath $Target -Encoding utf8
	Write-Host "Wrote $Target"
	return $Target
}

function Write-ApiIndex {
	$Target = Join-Path $ApiDir "README.md"
$Content = @'
# Ape API Docs

Generated by `tools/generate_api_docs.ps1`.

These docs are checked in so API drift is visible in normal diffs.

## Packages

- `raw/gfx_api.txt`: low-level graphics API symbols.
- `raw/app_api.txt`: minimal window/event facade used by the samples.
- `raw/shader_api.txt`: `.ashader` package loader and shader descriptor conversion.

## Markdown

- `markdown/gfx.md`: low-level graphics API reference.
- `markdown/app.md`: minimal window/event API reference.
- `markdown/shader.md`: shader package loader API reference.

## Status

The `gfx` docs are filtered with Odin private-file/private-symbol annotations for backend internals and include first-pass comments on the public API. The current decision is to keep `gfx` as the public package instead of adding a smaller facade package; explicit descriptors and handles are the intended low-level API. `tools/test_api_docs_public_surface.ps1` guards against backend internals leaking back into generated API docs.
'@

	Set-Content -LiteralPath $Target -Value $Content -Encoding utf8
	Write-Host "Wrote $Target"
}

$GfxRaw = Write-OdinDoc -Name "gfx_api" -PackagePath "gfx"
$AppRaw = Write-OdinDoc -Name "app_api" -PackagePath "app"
$ShaderRaw = Write-OdinDoc -Name "shader_api" -PackagePath "shader"
Convert-RawDocToMarkdown -Name "gfx" -Title "gfx" -RawPath $GfxRaw
Convert-RawDocToMarkdown -Name "app" -Title "app" -RawPath $AppRaw
Convert-RawDocToMarkdown -Name "shader" -Title "shader" -RawPath $ShaderRaw
Write-ApiIndex

Write-Host "Generated raw API docs in $OutputDir"
Write-Host "Generated Markdown API docs in $MarkdownOutputDir"
